<?php
/** @var \Scommerce\TrackingBase\Block\Checkout\Order $block */
/** @var \Scommerce\TrackingBase\ViewModel\Checkout\Multisuccess $viewModel */
$viewModel = $block->getData('view_model');
$viewModel->setBlock($block);
$helper = $viewModel->getHelper();
if (!($helper->isEnabled() && $helper->isEnhancedEcommerceEnabled())) {
    return;
}
?>
<script type="text/javascript"<?= /* @noEscape */ $helper->getNonce() ?>>
(function () {
    'use strict';
    const tracking = window.ScommerceHyva.getTracking();
    tracking.setPurchaseData(<?= /* @noEscape */ json_encode($viewModel->getPurchaseData(), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>);
    tracking.fire('page_ready', (tracking.getPageType() || 'purchase').toLowerCase());
})();
</script>
