<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Scommerce\TrackingBase\ViewModel\ViewProduct $viewModel */
$viewModel = $block->getData('view_model');
$viewModel->setBlock($block);
$helper = $viewModel->getHelper();
if (!$helper->isEnabled()) {
    return;
}
$cats = $viewModel->getRemarketingCategories();
?>
<script type="text/javascript"<?= /* @noEscape */ $helper->getNonce() ?>>
(function () {
    'use strict';
    const tracking = window.ScommerceHyva.getTracking();
    tracking.setData('category_full', <?= /* @noEscape */ json_encode((string) $cats['full']) ?>);
    tracking.setData('category_plain', <?= /* @noEscape */ json_encode((string) $cats['plain']) ?>);
    tracking.setProductData(<?= /* @noEscape */ json_encode($viewModel->getProductData(), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>);
    tracking.setImpressionListData(<?= /* @noEscape */ json_encode($viewModel->getRelatedProducts(), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>);
    tracking.setImpressionListData(<?= /* @noEscape */ json_encode($viewModel->getUpsellProducts(), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>);
    tracking.fire('page_ready', (tracking.getPageType() || 'product').toLowerCase());
})();
</script>
