<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Scommerce\TrackingBase\ViewModel\TrackingSliders $viewModel */
$viewModel = $block->getData('view_model');
$collection = $viewModel->getSlidersCollection();
if (!$collection) {
    return;
}
?>
<script type="text/javascript"<?= /* @noEscape */ $viewModel->getNonce() ?>>
window.ScommerceHyva.getTracking().setImpressionListData(
    <?= /* @noEscape */ json_encode($collection, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>
);
</script>
